#!/bin/bash

#./RunExperiment.sh workloada 201 202 1gb zipfian &>RunExperiment_1gb.log
#./RunExperiment.sh workloada 203 204 4gb zipfian &>RunExperiment_4gb.log
#./RunExperiment.sh workloada 205 206 8gb zipfian &>RunExperiment_8gb.log

#./RunExperiment.sh workloada 207 208 1gb uniform &>RunExperiment_uni_1gb.log
#./RunExperiment.sh workloada 209 210 2gb uniform &>RunExperiment_uni_2gb.log
#./RunExperiment.sh workloadc 211 212 1gb zipfian &>RunExperiment_workloadc_1gb.log
#./RunExperiment.sh workloada 213 214 1by2gb zipfian &>RunExperiment_workloada_1by2gb.log

#./RunExperiment.sh workloadc 215 216 4gb zipfian &>RunExperiment_workloadc_4gb.log
#./RunExperiment.sh workloadc 217 218 4gb zipfian &>RunExperiment_workloadc_6gb.log
#./RunExperiment.sh workloadc 219 220 2gb zipfian &>RunExperiment_workloadc_2gb.log
#./RunExperiment.sh workloadc 221 222 1by2gb zipfian &>RunExperiment_workloadc_1by2gb.log
#./RunExperiment.sh workloadc 223 224 6gb zipfian &>RunExperiment_workloadc_6gb.log

#./RunExperiment.sh workloadb 225 226 1by2gb zipfian &>RunExperiment_workloadb_1by2gb.log
#./RunExperiment.sh workloadb 227 228 1gb zipfian &>RunExperiment_workloadb_1gb.log
#./RunExperiment.sh workloadb 229 230 2gb zipfian &>RunExperiment_workloadb_2gb.log

#5k recordsize
#6gb heapsize
#./RunExperiment.sh workloada 231 232 1by2gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_1by2gb.log
#./RunExperiment.sh workloada 233 234 1by8gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_1by8gb.log
#./RunExperiment.sh workloada 235 236 1gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_1gb.log
#./RunExperiment.sh workloada 237 240 1by2gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_1by2gb.log
#./RunExperiment.sh workloada 237 238 2gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_2gb.log
#./RunExperiment.sh workloada 239 240 3gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_3gb.log
#./RunExperiment.sh scan 241 242 1by2gb_8gbVM zipfian &>RunExperiment_scan_8gbVM_1by2gb.log


