#!/bin/bash

#./RunExperiment.sh workloada 201 202 1gb zipfian &>RunExperiment_1gb.log
#./RunExperiment.sh workloada 203 204 4gb zipfian &>RunExperiment_4gb.log
#./RunExperiment.sh workloada 205 206 8gb zipfian &>RunExperiment_8gb.log

#./RunExperiment.sh workloada 207 208 1gb uniform &>RunExperiment_uni_1gb.log
#./RunExperiment.sh workloada 209 210 2gb uniform &>RunExperiment_uni_2gb.log
#./RunExperiment.sh workloadc 211 212 1gb zipfian &>RunExperiment_workloadc_1gb.log
#./RunExperiment.sh workloada 213 214 1by2gb zipfian &>RunExperiment_workloada_1by2gb.log

#./RunExperiment.sh workloadc 215 216 4gb zipfian &>RunExperiment_workloadc_4gb.log
#./RunExperiment.sh workloadc 217 218 4gb zipfian &>RunExperiment_workloadc_6gb.log
#./RunExperiment.sh workloadc 219 220 2gb zipfian &>RunExperiment_workloadc_2gb.log
#./RunExperiment.sh workloadc 221 222 1by2gb zipfian &>RunExperiment_workloadc_1by2gb.log
#./RunExperiment.sh workloadc 223 224 6gb zipfian &>RunExperiment_workloadc_6gb.log

#./RunExperiment.sh workloadb 225 226 1by2gb zipfian &>RunExperiment_workloadb_1by2gb.log
#./RunExperiment.sh workloadb 227 228 1gb zipfian &>RunExperiment_workloadb_1gb.log
#./RunExperiment.sh workloadb 229 230 2gb zipfian &>RunExperiment_workloadb_2gb.log

#5k recordsize
#6gb heapsize
#./RunExperiment.sh workloada 231 232 1by2gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_1by2gb.log
#./RunExperiment.sh workloada 233 234 1by8gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_1by8gb.log
#./RunExperiment.sh workloada 235 236 1gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_1gb.log
#./RunExperiment.sh workloada 237 240 1by2gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_1by2gb.log
#./RunExperiment.sh workloada 237 238 2gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_2gb.log
#./RunExperiment.sh workloada 239 240 3gb_8gbVM zipfian &>RunExperiment_workloada_8gbVM_3gb.log

#./RunExperiment.sh workloada 241 242 1by8gb zipfian &>RunExperiment_workloada_1gb_1.log
#./RunExperiment.sh workloada 243 244 1by8gb zipfian &>RunExperiment_workloada_1gb_2.log
#./RunExperiment.sh workloada 245 246 1by2gb zipfian &>RunExperiment_workloada_1by2gb.log
#./RunExperiment.sh workloada 247 248 1gb zipfian &>RunExperiment_workloada_1gb.log
#./RunExperiment.sh workloada 249 250 2gb zipfian &>RunExperiment_workloada_2gb.log
#./RunExperiment.sh workloada 251 252 4gb zipfian &>RunExperiment_workloada_4gb.log
#./RunExperiment.sh workloada 253 254 6gb zipfian &>RunExperiment_workloada_6gb.log
#./RunExperiment.sh workloada 255 256 6gb zipfian &>RunExperiment_workloada_6gb.log
#./RunExperiment.sh workloada 257 258 8gb zipfian &>RunExperiment_workloada_8gb.log

#./RunExperiment.sh workloadb 259 260 1by2gb zipfian &>RunExperiment_workloadb_1by2gb.log
#./RunExperiment.sh workloadb 261 262 1gb zipfian &>RunExperiment_workloadb_1gb.log
#./RunExperiment.sh workloadb 263 264 2gb zipfian &>RunExperiment_workloadb_2gb.log
#./RunExperiment.sh workloadb 265 266 4gb zipfian &>RunExperiment_workloadb_4gb.log
#./RunExperiment.sh workloadb 267 268 4gb zipfian &>RunExperiment_workloadb_4gb.log
#./RunExperiment.sh workloadb 269 270 6gb zipfian &>RunExperiment_workloadb_6gb.log

#./RunExperiment.sh workloadc 271 271 1by8gb zipfian &>RunExperiment_workloadb_1by8gb.log
#./RunExperiment.sh workloada 272 272 8.5gb zipfian &>RunExperiment_workloada_8.5gb.log
#./RunExperiment.sh workloada 273 273 9gb zipfian &>RunExperiment_workloada_9gb.log
#./RunExperiment.sh workloadc 274 274 1by8gb zipfian &>RunExperiment_workloadc_1by8gb.log
#./RunExperiment.sh workloadc 275 275 360mb zipfian &>RunExperiment_workloadc_360mb.log
#./RunExperiment.sh workloadb 276 276 7gb zipfian &>RunExperiment_workloadb_8gb.log
#./RunExperiment.sh workloadb 277 277 7.5gb zipfian &>RunExperiment_workloadb_8gb.log
#./RunExperiment.sh workloada 278 278 9.5gb zipfian &>RunExperiment_workloada_9.5gb.log
#./RunExperiment.sh workloadb 279 279 8gb zipfian &>RunExperiment_workloadb_8gb.log
#./RunExperiment.sh workloadc 280 280 1by8gb zipfian &>RunExperiment_workloadc_1by8gb.log
#./RunExperiment.sh workloadc 281 281 360mb  zipfian &>RunExperiment_workloadc_360mb.log
#./RunExperiment.sh workloadc 282 282 1by2gb zipfian &>RunExperiment_workloadc_1by2gb.log

#./RunExperiment.sh workloadc 283 283 1gb zipfian &>RunExperiment_workloadc_1gb.log
#./RunExperiment.sh workloada 284 284 8.5gb zipfian &>RunExperiment_workloada_8.5gb.log
#./RunExperiment.sh workloada 285 285 9gb zipfian &>RunExperiment_workloada_9gb.log
#./RunExperiment.sh workloada 286 286 9.5gb zipfian &>RunExperiment_workloada_9.5gb.log
#./RunExperiment.sh workloadc 287 287 1by8gb zipfian &>RunExperiment_workloadc_1by8gb.log
#./RunExperiment.sh workloadc 288 288 360mb zipfian &>RunExperiment_workloadc_360mb.log
#./RunExperiment.sh workloadb 289 289 7gb zipfian &>RunExperiment_workloadb_7gb.log
#./RunExperiment.sh workloadb 290 290 7.5gb zipfian &>RunExperiment_workloadb_7.5gb.log

#./RunExperiment.sh workloada 291 291 8.5gb zipfian &>RunExperiment_workloada_8.5gb.log
#./RunExperiment.sh workloada 292 292 9gb zipfian &>RunExperiment_workloada_9gb.log
#./RunExperiment.sh workloada 293 293 9.5gb zipfian &>RunExperiment_workloadb_9.5gb.log

#./RunExperiment.sh workloadc 294 294 2gb zipfian &>RunExperiment_workloadc_2gb.log
#./RunExperiment.sh workloadc 295 295 4gb zipfian &>RunExperiment_workloadc_4gb.log
#./RunExperiment.sh workloadc 296 296 6gb zipfian &>RunExperiment_workloadc_6gb.log

#./RunExperiment.sh workloadb 297 297 6gb zipfian &>RunExperiment_workloadb_6gb.log

#new version test
#./RunExperiment.sh workloadb 298 298 flex zipfian &>RunExperiment_default_flex.log
#./RunExperiment.sh workloadc 299 299 flex zipfian &>RunExperiment_default_flex.log
#./RunExperiment.sh workloada 300 300 flex zipfian &>RunExperiment_default_flex.log


#./RunExperiment.sh workloadb 301 301 flex zipfian &>RunExperiment_default_flex.log
#./RunExperiment.sh workloadc 302 302 flex zipfian &>RunExperiment_default_flex.log
#./RunExperiment.sh workloada 303 303 flex zipfian &>RunExperiment_default_flex.log
#./RunExperiment.sh workloadc 304 304 myflex zipfian &>RunExperiment_default_flex_just_printing.log
#./RunExperiment.sh workloadc 305 305 myflex zipfian &>RunExperiment_default_flex_testing.log
#./RunExperiment.sh workloadc 306 306 1gb zipfian &>RunExperiment_default_noflex_1gb_testing.log
#./RunExperiment.sh workloadc 307 307 myflex zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloadc 308 308 myflex zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloadb 309 309 myflex zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloadc 310 310 myflex zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloadb 311 311 myflex zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloada 312 312 myflex zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloadc 313 313 mydefault zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloadb 314 314 mydefault zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloadc 315 315 mydefault zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloadc 316 316 myflex zipfian &>RunExperiment_default_myflex_testing.log

#./RunExperiment.sh workloadc 317 317 mydefault zipfian &>RunExperiment_default_myflex_testing.log
#./RunExperiment.sh workloadc 318 318 myflex zipfian &>RunExperiment_default_myflex_testing.log.ini
#./RunExperiment.sh workloadc 319 319 myflex zipfian &>RunExperiment_default_myflex_testing.log.01
#./RunExperiment.sh workloadc 320 320 myflex zipfian &>RunExperiment_default_myflex_testing.log.005
#./RunExperiment.sh workloadc 330 330 myflex2 zipfian &>RunExperiment_default_myflex2_testing.log
#./RunExperiment.sh workloadc1 331 331 mydefault zipfian &>mydefault.log
#./RunExperiment.sh workloadc1 332 332 myflex3 zipfian 10 &>threshold_10.log
#./RunExperiment.sh workloadc1 333 333 myflex3 zipfian 20 &>threshold_20.log
#./RunExperiment.sh workloadc1 334 334 myflex3 zipfian 40 &>threshold_40.log
#./RunExperiment.sh workloadc1 335 335 myflex3 zipfian 60 &>threshold_60.log
#./RunExperiment.sh workloadc1 336 336 myflex3 zipfian 80 &>threshold_80.log
#./RunExperiment.sh workloadc1 337 337 myflex3 zipfian 100 &>threshold_100.log
#./RunExperiment.sh workloadc1 338 338 myflex3 zipfian 120 &>threshold_120.log
#./RunExperiment.sh workloadc1 339 339 myflex3 zipfian 200 &>threshold_200.log
#./RunExperiment.sh workloadc1 340 340 myflex3 zipfian 300 &>threshold_300.log
#./RunExperiment.sh workloadc1 341 341 myflex4 zipfian 700 20000 &>threshold_341.log
#./RunExperiment.sh workloadc1 342 342 myflex4 zipfian 700 20000 &>threshold_342.log
#./RunExperiment.sh workloadc1 343 343 myflex4 zipfian 700 20000 &>threshold_343.log
#./RunExperiment.sh workloadc1 344 344 myflex4 zipfian 700 20000 &>threshold_344.log
#./RunExperiment.sh workloadc1 345 345 myflex4 zipfian 700 20000 &>threshold_345.log
#./RunExperiment.sh workloadc1 346 346 myflex4 zipfian 700 1000 &>threshold_346.log
#./RunExperiment.sh workloadc1 347 347 myflex4 zipfian 700 500 &>threshold_347.log
#./RunExperiment.sh workloadc1 348 348 myflex4 zipfian 700 100 &>threshold_348.log
#./RunExperiment.sh workloadc1 349 349 myflex4 zipfian 700 100 &>threshold_349.log
#./RunExperiment.sh workloadc1 350 350 myflex4 zipfian 700 50 &>threshold_350.log
#./RunExperiment.sh workloadc1 351 351 myflex4 zipfian 700 200 &>threshold_351.log
#./RunExperiment.sh workloadc1 352 352 myflex4 zipfian 700 1000 &>threshold_352.log
#./RunExperiment.sh workloadc1 353 353 myflex4 zipfian 700 50 &>threshold_353.log
#./RunExperiment.sh workloadc1 354 354 myflex4 zipfian 700 50 &>threshold_354.log
#./RunExperiment.sh workloadc1 355 355 myflex4 zipfian 700 700 &>threshold_355.log
#./RunExperiment.sh workloadc1 356 356 myflex4 zipfian 700 0 &>threshold_356.log
#./RunExperiment.sh workloadc1 357 357 mydefault zipfian &>threshold_357.log
#./RunExperiment.sh workloadc1 358 358 myflex4 zipfian 700 200 &>threshold_358.log
#./RunExperiment.sh workloadc1 359 359 myflex4 zipfian 700 600 &>threshold_359.log
#./RunExperiment.sh workloadc1 360 360 myflex4 zipfian 700 600 &>threshold_360.log
#./RunExperiment.sh workloadc 361 361 myflex5 zipfian 10 &>threshold_361.log
#./RunExperiment.sh workloadc 362 362 myflex5 zipfian 20 &>threshold_362.log
#./RunExperiment.sh workloadc 363 363 myflex5 zipfian 40 &>threshold_363.log
#./RunExperiment.sh workloadc 364 364 myflex5 zipfian 60 &>threshold_364.log
#./RunExperiment.sh workloadc 365 365 myflex5 zipfian 70 &>threshold_365.log
#./RunExperiment.sh workloada 366 366 myflex5 zipfian 40 &>threshold_366.log
#./RunExperiment.sh workloadb 367 367 myflex5 zipfian 40 &>threshold_367.log
#./RunExperiment.sh workloadb 368 368 myflex5 zipfian 60 &>threshold_368.log
#./RunExperiment.sh workloadb 369 369 myflex5 zipfian 70 &>threshold_369.log
#./RunExperiment.sh workloada 370 370 myflex5 zipfian 60 &>threshold_370.log
#./RunExperiment.sh workloada 371 371 myflex5 zipfian 70 &>threshold_371.log
#./RunExperiment.sh workloada 372 372 myflex5 zipfian 10 &>threshold_372.log
#./RunExperiment.sh workloada 373 373 myflex5 zipfian 20 &>threshold_373.log
#./RunExperiment.sh workloadb 374 374 myflex5 zipfian 10 &>threshold_374.log
#./RunExperiment.sh workloadb 375 375 myflex5 zipfian 20 &>threshold_375.log
#./RunExperiment.sh workloada 376 376 myflex5 zipfian 75 &>threshold_376.log
#./RunExperiment.sh workloadb 377 377 myflex5 zipfian 75 &>threshold_377.log
#./RunExperiment.sh workloadc 378 378 myflex5 zipfian 75 &>threshold_378.log

#./RunExperiment.sh workloadc 379 379 myflex zipfian &>RunExperiment_myflex_logistic_379.log
#./RunExperiment.sh workloadb 380 380 myflex zipfian &>RunExperiment_myflex_logistic_380.log
#./RunExperiment.sh workloada 381 381 myflex zipfian &>RunExperiment_myflex_logistic_381.log
#./RunExperiment.sh workloadc 382 382 myflex zipfian &>RunExperiment_myflex_logistic_382_regions_included.log
#./RunExperiment.sh workloadb 383 383 myflex zipfian &>RunExperiment_myflex_logistic_383_regions_included.log
#./RunExperiment.sh workloada 384 384 myflex zipfian 90 &>RunExperiment_myflex_logistic_384_regions_included.log
#./RunExperiment.sh workloadc 385 385 myflex zipfian 10 &>RunExperiment_myflex_logistic_382_regions_included.log
#./RunExperiment.sh workloadb 386 386 myflex zipfian 50 &>RunExperiment_myflex_logistic_383_regions_included.log
#./RunExperiment.sh workloada 387 387 mydefault zipfian 90 &>RunExperiment_mydefault.log
#./RunExperiment.sh workloadb 388 388 mydefault zipfian 50 &>RunExperiment_mydefault.log
#./RunExperiment.sh workloadc 389 389 mydefault zipfian 10 &>RunExperiment_mydefault.log
#./RunExperiment.sh workloadc 390 390 myflex zipfian 10 &>RunExperiment_myflex_linear.log
#./RunExperiment.sh workloadc 391 391 myflex zipfian 10 &>RunExperiment_myflex_x_square.log
#./RunExperiment.sh workloadc 392 392 myflex zipfian 10 &>RunExperiment_myflex_1-pow_1-x_2.log
#./RunExperiment.sh workloadc 393 393 myflex zipfian 10 &>RunExperiment_myflex_1-pow_1-x_4.log
#./RunExperiment.sh workloadc 394 394 myflex zipfian 10 &>RunExperiment_myflex_1-pow_1-x_4.log
#./RunExperiment.sh workloadc 395 395 myflex zipfian 10 &>RunExperiment_myflex_1-pow_1-x_4_rs=1.log
./RunExperiment.sh workloadc1 396 396 myflex zipfian 1 &>RunExperiment_myflex_1-pow_1-x_4_rs=1.log
