#!/bin/bash

./RunExperiment.sh workloada 201 210 &>RunExperiment_8GB_MEM.log
#./RunExperiment.sh workloadc 178 180 &>RunExperiment_u4.log
#./RunExperiment.sh load 181 183 &>RunExperiment_5.log
#./RunExperiment.sh workloada 184 186 &>RunExperiment_u6.log
#./RunExperiment.sh workloadb 187 189 &>RunExperiment_u7.log
#./RunExperiment.sh workloadc 190 192 &>RunExperiment_u8.log
