#! /bin/bash

javac -cp ../lib/hadoop-common-2.4.0.jar:../lib/hbase-common-2.0.0-SNAPSHOT.jar:../lib/hbase-hadoop2-compat-2.0.0-SNAPSHOT.jar:../lib/hbase-server-2.0.0-SNAPSHOT.jar:../lib/hadoop-annotations-2.4.0.jar org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl.java

javac -cp ../lib/hadoop-common-2.4.0.jar:../lib/hbase-common-2.0.0-SNAPSHOT.jar:../lib/hbase-hadoop2-compat-2.0.0-SNAPSHOT.jar:../lib/hbase-server-2.0.0-SNAPSHOT.jar:../lib/hadoop-annotations-2.4.0.jar org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl2.java
javac -cp ../lib/hadoop-common-2.4.0.jar:../lib/hbase-common-2.0.0-SNAPSHOT.jar:../lib/hbase-hadoop2-compat-2.0.0-SNAPSHOT.jar:../lib/hbase-server-2.0.0-SNAPSHOT.jar:../lib/hadoop-annotations-2.4.0.jar org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl3.java
javac -cp ../lib/hadoop-common-2.4.0.jar:../lib/hbase-common-2.0.0-SNAPSHOT.jar:../lib/hbase-hadoop2-compat-2.0.0-SNAPSHOT.jar:../lib/hbase-server-2.0.0-SNAPSHOT.jar:../lib/hadoop-annotations-2.4.0.jar org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl4.java

javac -cp ../lib/hadoop-common-2.4.0.jar:../lib/hbase-common-2.0.0-SNAPSHOT.jar:../lib/hbase-hadoop2-compat-2.0.0-SNAPSHOT.jar:../lib/hbase-server-2.0.0-SNAPSHOT.jar:../lib/hadoop-annotations-2.4.0.jar org/apache/hadoop/hbase/regionserver/MyDefaultHeapMemoryTunerImpl.java
javac -cp ../lib/hadoop-common-2.4.0.jar:../lib/hbase-common-2.0.0-SNAPSHOT.jar:../lib/hbase-hadoop2-compat-2.0.0-SNAPSHOT.jar:../lib/hbase-server-2.0.0-SNAPSHOT.jar:../lib/hadoop-annotations-2.4.0.jar org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl5.java

jar cf selfdapql.jar org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl.class org/apache/hadoop/hbase/regionserver/MyDefaultHeapMemoryTunerImpl.class org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl2.class org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl3.class org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl4.class org/apache/hadoop/hbase/regionserver/MyHeapMemoryTunerImpl5.class

scp selfdapql.jar hadoop@9.1.143.58:~/hbase/.
scp selfdapql.jar hadoop@slave1:~/hbase/.
